- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: Remove the nodejs package
      ansible.builtin.package:
        name: nodejs
        state: absent
    
    - name: enable nodejs-18
      ansible.builtin.service:
        name: nodejs-18
        enabled: yes

    - name: Install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present
    
    