- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: Remove the nodejs package
      ansible.builtin.package:
        name: nodejs
        state: absent

    - name: enable 18 version of nodejs
      ansible.builtin.command: dnf module enable nodejs:18 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Add the user 'roboshop'
      ansible.builtin.user:
        name: roboshop

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name: Download catalogue.zip
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp

    - name: Unarchive catalogue.zip in app directory
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        # remote_src: yes 
    