- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: Remove the nodejs package
      ansible.builtin.package:
        name: nodejs
        state: absent

    - name: Install 18 version of nodejs
      ansible.builtin.command: dnf module enable nodejs:18 -y
      
    